# Generated by Django 3.2 on 2021-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpermission_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='permis',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='permis',
            field=models.ManyToManyField(to='users.UserPermission'),
        ),
    ]
