# Generated by Django 3.2 on 2021-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210717_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
