# Generated by Django 3.2 on 2021-07-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210720_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='permis',
            field=models.ManyToManyField(blank=True, to='users.UserPermission'),
        ),
    ]
