# Generated by Django 3.2 on 2021-07-17 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'productgroup',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40, unique=True)),
                ('qnt_in_box', models.IntegerField(max_length=10)),
                ('kg_single', models.DecimalField(decimal_places=2, max_digits=20)),
                ('kg_box', models.DecimalField(decimal_places=2, max_digits=20)),
                ('info_1', models.CharField(max_length=100)),
                ('info_2', models.CharField(max_length=100)),
                ('info_3', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AlterField(
            model_name='partgroups',
            name='part_group',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='partgroups',
            constraint=models.UniqueConstraint(fields=('main_type', 'part_group'), name='unique_fields'),
        ),
        migrations.AddField(
            model_name='products',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.maingroup'),
        ),
        migrations.AddField(
            model_name='products',
            name='part_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partgroup', to='products.partgroups'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productgroup', to='products.productgroup'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('category', 'part_group', 'product_group'), name='unique_info'),
        ),
    ]
