# Generated by Django 3.2 on 2021-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210717_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qnt_in_box',
            field=models.IntegerField(),
        ),
    ]
