# Generated by Django 3.2 on 2021-07-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210717_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partgroups',
            name='main_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintypes', to='products.maingroup'),
        ),
    ]
