# Generated by Django 3.2 on 2021-07-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_partgroups_main_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.maingroup'),
        ),
        migrations.AlterField(
            model_name='products',
            name='part_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partgroup', to='products.partgroups'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productgroup', to='products.productgroup'),
        ),
    ]
